# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategories',
            name='id',
        ),
        migrations.AlterField(
            model_name='newscategories',
            name='cname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
