# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170911_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategories',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newscategories',
            name='cname',
            field=models.CharField(max_length=100),
        ),
    ]
