# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170824_0923'),
    ]

    operations = [
    ]
