# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20170828_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategories',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newscategories',
            name='cname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
