# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20170828_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategories',
            name='id',
        ),
        migrations.AlterField(
            model_name='newscategories',
            name='cname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
