# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20170828_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ImageField(blank=True, upload_to=b'homepage/modelimages/'),
        ),
    ]
