# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20170828_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='modelimages/'),
        ),
    ]
