# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_auto_20170830_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_rel_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='modelimages/')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='images',
        ),
        migrations.AddField(
            model_name='news_rel_image',
            name='rel_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homepage.News'),
        ),
    ]
