# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20170830_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsrelimage',
            old_name='rel_image',
            new_name='rel_news',
        ),
    ]
