# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_auto_20170906_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
