# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_auto_20170906_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsrelimage',
            name='rel_news',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homepage.News'),
        ),
    ]
