# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_auto_20170907_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank='True', upload_to='attachments/')),
                ('is_first', models.BooleanField(default=False)),
                ('is_second', models.BooleanField(default=False)),
                ('news_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images1', to='homepage.News')),
            ],
        ),
    ]
