# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank='True', upload_to='modelimages/'),
        ),
    ]
