# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_auto_20170907_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='modelimages/'),
        ),
    ]
