# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0032_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, upload_to='modelimages/'),
        ),
    ]
