# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_auto_20170907_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.RemoveField(
            model_name='image',
            name='news_rel',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
