# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0036_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(upload_to='modelimages/'),
        ),
    ]
