# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0037_auto_20170908_0527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='newsrelimage',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='modelimages/'),
        ),
    ]
