# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0038_auto_20170908_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='modelimages/')),
                ('is_first', models.BooleanField(default=False)),
                ('is_second', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homepage.News')),
            ],
        ),
        migrations.CreateModel(
            name='Newsrelimage1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(blank=True, null=True, upload_to='modelimages/')),
                ('rel_news1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images1', to='homepage.News')),
            ],
        ),
        migrations.AlterField(
            model_name='newsrelimage',
            name='rel_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images11', to='homepage.News'),
        ),
    ]
