# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0039_auto_20170908_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.AlterField(
            model_name='newsrelimage',
            name='rel_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homepage.News'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
