# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0040_auto_20170908_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsrelimage1',
            name='rel_news1',
        ),
        migrations.DeleteModel(
            name='Newsrelimage1',
        ),
    ]
