# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0043_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='content',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
