# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0044_auto_20170911_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
