# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0045_auto_20170911_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
